import { randomUUID } from 'node:crypto';
export class TeamRepository {
  constructor(db) { this.db=db;this.listCache=new Map();this.listTtlMs=8_000; }
  _clear(){this.listCache.clear();}
  async list(guildId, { activeOnly = true, includeDeleted = false } = {}) {
    const key=`${guildId}:${activeOnly?1:0}:${includeDeleted?1:0}`;const hit=this.listCache.get(key);if(hit&&hit.expiresAt>Date.now())return hit.value;
    const { rows } = await this.db.query(`SELECT t.*, count(tm.user_id) FILTER (WHERE tm.active) AS member_count
      FROM teams t LEFT JOIN team_members tm ON tm.team_id=t.id
      WHERE t.guild_id=$1 ${activeOnly ? 'AND t.active=true' : ''} ${includeDeleted ? '' : 'AND t.deleted_at IS NULL'}
      GROUP BY t.id ORDER BY t.name`, [guildId]);
    this.listCache.set(key,{value:rows,expiresAt:Date.now()+this.listTtlMs});return rows;
  }
  async get(id) { const { rows } = await this.db.query('SELECT * FROM teams WHERE id=$1', [id]); return rows[0] ?? null; }
  async findByDiscordRole(guildId, roleId) { const { rows } = await this.db.query('SELECT * FROM teams WHERE guild_id=$1 AND discord_role_id=$2 AND deleted_at IS NULL LIMIT 1',[guildId,roleId]); return rows[0] ?? null; }
  async findByName(guildId, name) { const { rows } = await this.db.query('SELECT * FROM teams WHERE guild_id=$1 AND lower(name)=lower($2) AND deleted_at IS NULL LIMIT 1',[guildId,name]); return rows[0] ?? null; }
  async create({ guildId, name, description, actorId, sourceType='manual' }, client = this.db) {const id=randomUUID();const {rows}=await client.query(`INSERT INTO teams(id,guild_id,name,description,created_by,source_type) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[id,guildId,name,description,actorId,sourceType]);this._clear();return rows[0];}
  async rename(id, name, client=this.db) { const { rows }=await client.query('UPDATE teams SET name=$2,updated_at=now() WHERE id=$1 RETURNING *',[id,name]);this._clear();return rows[0]; }
  async setActive(id, active, client=this.db) { const { rows }=await client.query('UPDATE teams SET active=$2,updated_at=now() WHERE id=$1 RETURNING *',[id,active]);this._clear();return rows[0]; }
  async addMember({ guildId, teamId, userId }, client=this.db) {await client.query(`INSERT INTO team_members(team_id,guild_id,user_id) VALUES($1,$2,$3) ON CONFLICT(team_id,user_id) DO UPDATE SET active=true`,[teamId,guildId,userId]);this._clear();}
  async removeMember({ teamId, userId }, client=this.db) {await client.query('UPDATE team_members SET active=false WHERE team_id=$1 AND user_id=$2',[teamId,userId]);this._clear();}
  async updateDiscordLinks(id, patch, client=this.db) {const allowed=new Set(['discord_role_id','default_voice_channel_id','notification_channel_id','source_type']);const entries=Object.entries(patch).filter(([k])=>allowed.has(k));if(!entries.length)return this.get(id);const sets=entries.map(([k],idx)=>`${k}=$${idx+2}`).join(', ');const values=entries.map(([,v])=>v);const {rows}=await client.query(`UPDATE teams SET ${sets},updated_at=now() WHERE id=$1 RETURNING *`,[id,...values]);this._clear();return rows[0]??null;}
  async linkedTeams(guildId) {const {rows}=await this.db.query(`SELECT * FROM teams WHERE guild_id=$1 AND active=true AND deleted_at IS NULL AND discord_role_id IS NOT NULL ORDER BY name`,[guildId]);return rows;}
  async teamsForUser(guildId,userId) {const { rows } = await this.db.query(`SELECT t.* FROM teams t JOIN team_members tm ON tm.team_id=t.id WHERE tm.guild_id=$1 AND tm.user_id=$2 AND tm.active=true AND t.active=true AND t.deleted_at IS NULL ORDER BY t.name`,[guildId,userId]);return rows;}
  async members(teamId) {const { rows } = await this.db.query(`SELECT u.id AS user_id, COALESCE(u.display_name,u.username,u.id::text) AS display_name FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=$1 AND tm.active=true ORDER BY display_name`,[teamId]);return rows;}
  async markDeleted({teamId,actorId,reason='حذف من Meeting 967'},client=this.db){const {rows}=await client.query(`UPDATE teams SET active=false,deleted_at=now(),deleted_by=$2,delete_reason=$3,updated_at=now() WHERE id=$1 AND deleted_at IS NULL RETURNING *`,[teamId,actorId,reason]);this._clear();return rows[0]??null;}
  async excludeDiscordRole({guildId,roleId,actorId,reason='تم حذف الفريق من Meeting 967'},client=this.db){await client.query(`INSERT INTO team_sync_exclusions(guild_id,discord_role_id,excluded_by,reason) VALUES($1,$2,$3,$4) ON CONFLICT(guild_id,discord_role_id) DO UPDATE SET excluded_by=EXCLUDED.excluded_by,reason=EXCLUDED.reason,created_at=now()`,[guildId,roleId,actorId,reason]);}
  async excludedDiscordRoleIds(guildId){const {rows}=await this.db.query('SELECT discord_role_id FROM team_sync_exclusions WHERE guild_id=$1',[guildId]);return rows.map(r=>String(r.discord_role_id));}
  async mergeInto(sourceId,targetId,client=this.db){if(String(sourceId)===String(targetId))return;const {rows}=await client.query('SELECT id,guild_id FROM teams WHERE id=ANY($1::uuid[])',[[sourceId,targetId]]);if(rows.length!==2)throw new Error('تعذر دمج الفريق المكرر لأن أحد الفريقين غير موجود.');if(String(rows[0].guild_id)!==String(rows[1].guild_id))throw new Error('لا يمكن دمج فريقين من سيرفرين مختلفين.');await client.query(`INSERT INTO team_members(team_id,guild_id,user_id,active,joined_at) SELECT $2,guild_id,user_id,active,joined_at FROM team_members WHERE team_id=$1 ON CONFLICT(team_id,user_id) DO UPDATE SET active=(team_members.active OR EXCLUDED.active)`,[sourceId,targetId]);await client.query('UPDATE meetings SET team_id=$2 WHERE team_id=$1',[sourceId,targetId]);await client.query('UPDATE meeting_member_snapshots SET team_id=$2 WHERE team_id=$1',[sourceId,targetId]);await client.query('UPDATE meeting_tasks SET team_id=$2 WHERE team_id=$1',[sourceId,targetId]).catch(error=>{if(error?.code!=='42P01')throw error;});await client.query('UPDATE task_assignment_groups SET origin_team_id=$2 WHERE origin_team_id=$1',[sourceId,targetId]).catch(error=>{if(error?.code!=='42P01')throw error;});await client.query('UPDATE task_assignment_groups SET target_team_id=$2 WHERE target_team_id=$1',[sourceId,targetId]).catch(error=>{if(error?.code!=='42P01')throw error;});await client.query(`INSERT INTO team_permissions(guild_id,team_id,permission_key,effect,scope_type,scope_id,granted_by,created_at) SELECT guild_id,$2,permission_key,effect,scope_type,CASE WHEN scope_type='team' AND scope_id=$1::text THEN $2::text ELSE scope_id END,granted_by,created_at FROM team_permissions WHERE team_id=$1 ON CONFLICT DO NOTHING`,[sourceId,targetId]);await client.query(`INSERT INTO user_permissions(guild_id,user_id,permission_key,effect,scope_type,scope_id,granted_by,created_at) SELECT guild_id,user_id,permission_key,effect,scope_type,$2::text,granted_by,created_at FROM user_permissions WHERE scope_type='team' AND scope_id=$1::text ON CONFLICT DO NOTHING`,[sourceId,targetId]);await client.query(`DELETE FROM user_permissions WHERE scope_type='team' AND scope_id=$1::text`,[sourceId]);await client.query(`INSERT INTO role_permissions(guild_id,role_id,permission_key,effect,scope_type,scope_id,granted_by,created_at) SELECT guild_id,role_id,permission_key,effect,scope_type,$2::text,granted_by,created_at FROM role_permissions WHERE scope_type='team' AND scope_id=$1::text ON CONFLICT DO NOTHING`,[sourceId,targetId]);await client.query(`DELETE FROM role_permissions WHERE scope_type='team' AND scope_id=$1::text`,[sourceId]);await client.query('DELETE FROM teams WHERE id=$1',[sourceId]);this._clear();}
}
