import {ActionRowBuilder,ModalBuilder,TextInputBuilder,TextInputStyle,ButtonStyle} from 'discord.js';
import {e,btn,rowsFromButtons,stringSelect,withNavigation} from '../ui.js';
import {subjectFromInteraction} from '../context.js';
import {formatDate} from '../../../utils/time.js';
const input=(id,label,style=TextInputStyle.Paragraph,required=true)=>new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(required));
export async function handleExcuses(i,a){const id=i.customId??'';const s=await subjectFromInteraction(i,a.env);
  if(id==='member:excuse')return chooseMeeting(i,a,s);if(id==='member:excuses')return mine(i,a,s);if(id==='excuse:meeting')return reasonModal(i,a,s,i.values[0]);if(id.startsWith('excuse:submit:'))return submit(i,a,s,id.split(':')[2]);if(id==='admin:excuses')return pending(i,a,s);if(id==='excuse:review')return review(i,a,s,i.values[0]);if(id.startsWith('excuse:approve:'))return decisionModal(i,a,s,id.split(':')[2],'approved');if(id.startsWith('excuse:reject:'))return decisionModal(i,a,s,id.split(':')[2],'rejected');if(id.startsWith('excuse:decision:')){const parts=id.split(':');return decide(i,a,s,parts[2],parts[3]);}return false;}
async function chooseMeeting(i,a,s){const meetings=await a.meetings.listForUser(s.guildId,s.userId,{future:true});const allowed=meetings.filter(m=>['upcoming','postponed'].includes(m.status));if(!allowed.length)return i.update({embeds:[e('📝 تقديم اعتذار','لا توجد اجتماعات قادمة متاحة للاعتذار.')],components:withNavigation([],'member:excuses')});return i.update({embeds:[e('📝 تقديم اعتذار','اختر الاجتماع.')],components:withNavigation([stringSelect('excuse:meeting','الاجتماع',allowed.map(m=>({label:m.name.slice(0,100),description:m.team_name.slice(0,100),value:m.id})))],'member:excuses')});}
async function reasonModal(i,a,s,meetingId){const modal=new ModalBuilder().setCustomId(`excuse:submit:${meetingId}`).setTitle('سبب الاعتذار').addComponents(input('reason','سبب الاعتذار'));return i.showModal(modal);}
async function submit(i,a,s,meetingId){a.rateLimiter.consume(`excuse:${s.userId}`,{limit:3,windowMs:60_000});const ex=await a.excuseService.submit({guildId:s.guildId,userId:s.userId,meetingId,reason:i.fields.getTextInputValue('reason')});return i.reply({content:`✅ تم إرسال الاعتذار. الحالة: **Pending**\nالمعرف: \`${ex.id}\``,components:withNavigation([],'member:excuses'),ephemeral:Boolean(i.guildId)});}
async function mine(i,a,s){const rows=await a.excuses.listForUser(s.guildId,s.userId);const settings=await a.guilds.getSettings(s.guildId);const ar={pending:'قيد المراجعة',approved:'مقبول',rejected:'مرفوض'};return i.update({embeds:[e('📝 اعتذاراتي',rows.length?rows.map(x=>`• **${x.meeting_name}** — ${formatDate(x.scheduled_at,settings.timezone)} — **${ar[x.status]}**`).join('\n'):'لا توجد اعتذارات.')],components:withNavigation(rowsFromButtons([btn('member:excuse','تقديم اعتذار',2,'➕')]))});}
async function pending(i,a,s){await a.permissionService.assertPotential(s,'excuses.view');const rows=await a.excuses.listPending(s.guildId);const visible=[];for(const x of rows)if(await a.permissionService.has(s,'excuses.view',{teamId:x.team_id,meetingId:x.meeting_id}))visible.push(x);if(!visible.length)return i.update({embeds:[e('📨 الاعتذارات','لا توجد طلبات Pending ضمن نطاق صلاحيتك.')],components:withNavigation([])});return i.update({embeds:[e('📨 الاعتذارات','اختر طلبًا للمراجعة.')],components:withNavigation([stringSelect('excuse:review','طلب الاعتذار',visible.map(x=>({label:x.member_name.slice(0,100),description:`${x.team_name} • ${x.meeting_name}`.slice(0,100),value:x.id})))])});}
async function review(i,a,s,id){const x=await a.excuses.get(id);await a.permissionService.assert(s,'excuses.view',{teamId:x.team_id,meetingId:x.meeting_id});const canA=await a.permissionService.has(s,'excuses.approve',{teamId:x.team_id,meetingId:x.meeting_id});const canR=await a.permissionService.has(s,'excuses.reject',{teamId:x.team_id,meetingId:x.meeting_id});const buttons=[];if(canA)buttons.push(btn(`excuse:approve:${id}`,'قبول',ButtonStyle.Success,'✅'));if(canR)buttons.push(btn(`excuse:reject:${id}`,'رفض',ButtonStyle.Danger,'❌'));return i.update({embeds:[e('مراجعة اعتذار',`العضو: <@${x.user_id}>\nالفريق: **${x.team_name}**\nالاجتماع: **${x.meeting_name}**\nالسبب: ${x.reason}`)],components:withNavigation(rowsFromButtons(buttons),'admin:excuses')});}
async function decisionModal(i,a,s,id,status){const x=await a.excuses.get(id);await a.permissionService.assert(s,status==='approved'?'excuses.approve':'excuses.reject',{teamId:x.team_id,meetingId:x.meeting_id});return i.showModal(new ModalBuilder().setCustomId(`excuse:decision:${id}:${status}`).setTitle(status==='approved'?'قبول الاعتذار':'رفض الاعتذار').addComponents(input('note','ملاحظة القرار',TextInputStyle.Paragraph,false)));}
async function decide(i,a,s,id,status){const x=await a.excuses.get(id);await a.permissionService.assert(s,status==='approved'?'excuses.approve':'excuses.reject',{teamId:x.team_id,meetingId:x.meeting_id});await a.excuseService.decide({guildId:s.guildId,id,status,actorId:s.userId,note:i.fields.getTextInputValue('note')});return i.reply({content:`✅ تم ${status==='approved'?'قبول':'رفض'} الاعتذار.`,components:withNavigation([],'admin:excuses'),ephemeral:Boolean(i.guildId)});}
