import fs from 'node:fs/promises';
import {e,stringSelect,btn,rowsFromButtons,withNavigation} from '../ui.js';
import {subjectFromInteraction} from '../context.js';
export async function handleReports(i,a){const id=i.customId??'';const s=await subjectFromInteraction(i,a.env);
  if(id==='admin:reports')return list(i,a,s);if(id==='report:meeting')return open(i,a,s,i.values[0]);if(id.startsWith('report:view:'))return open(i,a,s,id.split(':')[2]);if(id.startsWith('report:generate:'))return generate(i,a,s,id.split(':')[2]);if(id.startsWith('report:download:'))return download(i,a,s,id.split(':')[2]);return false;}
async function list(i,a,s){await a.permissionService.assertPotential(s,'reports.view');const ms=await a.meetings.listForGuild(s.guildId,{statuses:['ended'],limit:25});const visible=[];for(const m of ms)if(await a.permissionService.has(s,'reports.view',{teamId:m.team_id,meetingId:m.id}))visible.push(m);if(!visible.length)return i.update({embeds:[e('📄 التقارير','لا توجد اجتماعات منتهية متاحة.')],components:withNavigation([])});return i.update({embeds:[e('📄 التقارير','اختر اجتماعًا.')],components:withNavigation([stringSelect('report:meeting','الاجتماع',visible.map(m=>({label:m.name.slice(0,100),description:m.team_name.slice(0,100),value:m.id})))])});}
async function open(i,a,s,meetingId){const m=await a.meetings.get(meetingId);await a.permissionService.assert(s,'reports.view',{teamId:m.team_id,meetingId});const r=await a.reports.latest(meetingId);const buttons=[];if(await a.permissionService.has(s,'reports.generate',{teamId:m.team_id,meetingId}))buttons.push(btn(`report:generate:${meetingId}`,'توليد تقرير جديد',2,'🔄'));if(r&&await a.permissionService.has(s,'reports.download',{teamId:m.team_id,meetingId}))buttons.push(btn(`report:download:${meetingId}`,'تنزيل آخر تقرير',2,'⬇️'));return i.update({embeds:[e(`📄 ${m.name}`,r?`آخر تقرير: ${r.generated_at.toISOString()}\nSHA256: \`${r.sha256.slice(0,16)}…\``:'لا يوجد تقرير محفوظ حتى الآن.')],components:withNavigation(rowsFromButtons(buttons),'admin:reports')});}
async function generate(i,a,s,meetingId){const m=await a.meetings.get(meetingId);await a.permissionService.assert(s,'reports.generate',{teamId:m.team_id,meetingId});await i.deferReply({ephemeral:Boolean(i.guildId)});const r=await a.reportService.generate({guildId:s.guildId,meetingId,actorId:s.userId,guild:s.guild});return i.editReply({content:'✅ تم إنشاء التقرير.',files:[r.path],components:withNavigation([],`report:view:${meetingId}`)});}
async function download(i,a,s,meetingId){const m=await a.meetings.get(meetingId);await a.permissionService.assert(s,'reports.download',{teamId:m.team_id,meetingId});const r=await a.reports.latest(meetingId);if(!r)return i.reply({content:'لا يوجد تقرير.',components:withNavigation([],`report:view:${meetingId}`),ephemeral:Boolean(i.guildId)});await fs.access(r.path);return i.reply({content:'📄 آخر تقرير:',files:[r.path],components:withNavigation([],`report:view:${meetingId}`),ephemeral:Boolean(i.guildId)});}
